### ISSUE TITLE
Compilation failure with Rust 1.88.0 due to lifetime capture in impl Trait return types

### ISSUE THREAD

**Issue by rsharath** [VirusTotal/yara-x#416]
yara-x-parser fails to compile with Rust 1.88.0 due to stricter lifetime checking for impl Trait return types. This appears to be related to the Rust issue  **[rust-lang/rust#63033.](https://github.com/rust-lang/rust/issues/63033)**

###   Error:
  error[E0700]: hidden type for `impl Iterator<Item = cst::Node<M>>` captures lifetime that does not appear in bounds
     --> yara-x-parser-1.4.0/src/cst/mod.rs:451:9
      |
  450 |     pub fn ancestors(&self) -> impl Iterator<Item = Node<M>> {
      |                      -----     ----------------------------- opaque type defined here
      |                      |
      |                      hidden type captures the anonymous lifetime defined here
  451 |         self.inner.parent_ancestors().map(Node::new)
      |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
  help: add a `use<...>` bound to explicitly capture `'_`
      |
  450 |     pub fn ancestors(&self) -> impl Iterator<Item = Node<M>> + use<'_, M> {
      |                                                              ++++++++++++

### **Affected files:**
  - parser/src/cst/mod.rs lines 450, 815, and 864

###   **Environment:**
  - Rust version: 1.88.0 (6b00bc388 2025-06-23)
  - yara-x version: 1.4.0
  - Platform: macOS (also affects other platforms)

###   **Suggested fix:**
  The Rust compiler suggests adding explicit lifetime capture using the use<...> syntax:

  **// Current (broken):**
  pub fn ancestors(&self) -> impl Iterator<Item = Node<M>> {

  **// Fixed:**
  pub fn ancestors(&self) -> impl Iterator<Item = Node<M>> + use<'_, M> {

  This needs to be applied to three functions in parser/src/cst/mod.rs:
  1. ancestors() at line 450
  2. siblings() at line 815
  3. siblings_with_tokens() at line 864

###   **Workaround:**
  Currently users need to downgrade to an older Rust version or use yara-x 0.10.x to avoid this compilation error.

**Comment by plusvic** [comment]
This is strange, I'm unable to reproduce the issue with exactly the same Rust version (rustc 1.88.0 (6b00bc388 2025-06-23)) in macOS. I tried also with a newer version, and we both the yara-x 1.4.0 and the current master branch, and everything worked fine. Can you double check that you are actually using rustc 1.88.0?

**Comment by latonis** [comment]
I also did not run in to this, just compiled with 1.88.0:

`stable-aarch64-apple-darwin unchanged - rustc 1.88.0 (6b00bc388 2025-06-23)`

**Comment by I-Alzamil** [comment]
I'm facing the same issue in windows.

### Environment:
- Rust version: stable-x86_64-pc-windows-msvc - 1.88.0 (6b00bc388 2025-06-23)
- yara-x version: 1.4.0
- Platform: Windows 11 23H2 (OS Build 22631.5624)
- MSVC: v143

### Build logs:

```
   Compiling x509-parser v0.17.0
   Compiling annotate-snippets v0.11.5
   Compiling yara-x-parser v1.4.0
   Compiling rsa v0.9.8
error[E0700]: hidden type for `impl Iterator<Item = cst::Node<M>>` captures lifetime that does not appear in bounds
   --> C:\Users\USER\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\yara-x-parser-1.4.0\src\cst\mod.rs:451:9
    |
450 |     pub fn ancestors(&self) -> impl Iterator<Item = Node<M>> {
    |                      -----     ----------------------------- opaque type defined here
    |                      |
    |                      hidden type `std::iter::Map<impl Iterator<Item = rowan::SyntaxNode<YARA>>, fn(rowan::SyntaxNode<YARA>) -> cst::Node<M> {cst::Node::<M>::new}>` captures the anonymous lifetime defined here
451 |         self.inner.parent_ancestors().map(Node::new)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: add a `use<...>` bound to explicitly capture `'_`
    |
450 |     pub fn ancestors(&self) -> impl Iterator<Item = Node<M>> + use<'_, M> {
    |                                                              ++++++++++++

error[E0700]: hidden type for `impl Iterator<Item = cst::Node<M>>` captures lifetime that does not appear in bounds
   --> C:\Users\USER\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\yara-x-parser-1.4.0\src\cst\mod.rs:824:9
    |
813 |         &self,
    |         ----- hidden type `std::iter::Map<std::iter::Skip<impl Iterator<Item = rowan::SyntaxNode<YARA>>>, fn(rowan::SyntaxNode<YARA>) -> cst::Node<M> {cst::Node::<M>::new}>` captures the anonymous lifetime defined here  
814 |         direction: Direction,
815 |     ) -> impl Iterator<Item = Node<M>> {
    |          ----------------------------- opaque type defined here
...
824 |         self.inner.siblings(direction).skip(1).map(Node::new)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: add a `use<...>` bound to explicitly capture `'_`
    |
815 |     ) -> impl Iterator<Item = Node<M>> + use<'_, M> {
    |                                        ++++++++++++

error[E0700]: hidden type for `impl Iterator<Item = cst::NodeOrToken<M>>` captures lifetime that does not appear in bounds
   --> C:\Users\USER\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\yara-x-parser-1.4.0\src\cst\mod.rs:873:9
    |
862 |         &self,
    |         ----- hidden type `std::iter::Map<std::iter::Skip<impl Iterator<Item = rowan::NodeOrToken<rowan::SyntaxNode<YARA>, rowan::SyntaxToken<YARA>>>>, {closure@C:\Users\USER\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\yara-x-parser-1.4.0\src\cst\mod.rs:873:64: 873:67}>` captures the anonymous lifetime defined here
863 |         direction: Direction,
864 |     ) -> impl Iterator<Item = NodeOrToken<M>> {
    |          ------------------------------------ opaque type defined here
...
873 |         self.inner.siblings_with_tokens(direction).skip(1).map(|x| x.into())
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: add a `use<...>` bound to explicitly capture `'_`
    |
864 |     ) -> impl Iterator<Item = NodeOrToken<M>> + use<'_, M> {
    |                                               ++++++++++++

   Compiling yara-x v1.4.0
   Compiling linkme v0.3.33
   Compiling memx v0.1.32
   Compiling p384 v0.13.1
For more information about this error, try `rustc --explain E0700`.
error: could not compile `yara-x-parser` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by plusvic** [comment]
This is really, really weird. I tried to reproduce this in a Windows machine with Rust 1.88 and didn't get any error. Are you building with the standard `cargo build` command?

**Comment by I-Alzamil** [comment]
Yeah, you are right this is very weird😅. I did a fresh install with Windows in a VM, and it worked fine. 

I also managed to fix the issue in my main machine by doing the following:

- Uninstall rustup using following command:
`rustup self uninstall`
- Reboot.
- Reinstall rustup.
- Any new package created after this should work.
- For existing packages, delete both Cargo.lock file and Target folder (Error still show up if not).

This fix worked for me in Windows, so I don't know if it would work with others.

**Comment by plusvic** [comment]
Then I'm closing this issue because it looks like some issue with `rustc` itself.
